### PR TITLE
Japanese translation of great mod

### PR DESCRIPTION
**Pull request by CKenJa**
"gui.figura.config.nametagicon": "ネームタグのアイコン表示",
"gui.figura.config.tooltip.nametagicon": "Figura使用者の%dに△マークを表示するか",
Is this key not working?
This was not reflected during the resorcepack test

### CODE REVIEW

**Comment by Francy-chan** [comment]
> 
> 
> "gui.figura.config.nametagicon": "ネームタグのアイコン表示",
> "gui.figura.config.tooltip.nametagicon": "Figura使用者の%dに△マークを表示するか",
> Is this key not working?
> This was not reflected during the resorcepack test

it seems to be working correctly, both of them

**Comment by CKenJa** [comment]
I just checked it and it was working.
i think this is due to a mistake in the resource pack.
i am sorry

**Comment by CookiePlays0** [comment]
since this seems to be resolved it should be closed ;-;

**Review by Francy-chan — CHANGES_REQUESTED** [review]
translations seems to be outdated with the current en_US file

**Comment by CKenJa** [comment]
I made translation for new file. 
I will add commit after debug it.
By the way, is it ok to translate 信頼(trust) as 権限(authority)?

**Comment by Francy-chan** [comment]
> By the way, is it ok to translate 信頼(trust) as 権限(authority)?
if it explain things for the reader, and keeps the same idea of what it is, it is okay to make those type of changes

**Pull request merged**
